### ISSUE TITLE
Upgrade strategy

### ISSUE THREAD

**Issue by zaibon** [zero-os/home#95]
0-OS is designed to be used in a decentralized architecture. Each node running 0-OS is owned by a different person and there is no central authority that controls all the nodes. This makes the upgrade of such an ecosystem pretty hard. 

In 0-OS as of today we can identify 3 layers of software component that need to be upgraded:

- 0-OS kernel: this is the lowest layer, it contains the Linux kernel, all the software used for networking, virtualization and all the logic of [0-Core](https://github.com/zero-os/0-core). 0-Core being responsible to expose the primitives of the OS over the redis interface.
- SAL layer: this layer live in jumpscale and holds all the logic that will be used by the node robot. The SAL are build on top of the low level primitives given by 0-Core
- Robot layer: This is the all the template running by the 0-robot. Templates combine the different SAL to allow to manage the state of the 0-OS and provide a public interface over a REST API.

These 3 layers all have different versions, distribution and upgrade methods.
- The kernel layer require a reboot to be upgraded
- the SAL layer requires to restart the container running the robot with a new flist
- the templates need to be pulled from GitHub and reloaded inside the robots

Something to notice is that it can happens that a change in any of these layer impact the 3 layers. 

Example: The code used by the templates of the 0-robot comes from the flist that the 0-robot uses. Which means we could have a situation where the templates requires a newer version of the Jumpscale SAL that is not present in the flist of the 0-robot while the version of the 0-robot itself doesn't change. This makes these 2 layers pretty much depending on each other for the wrong reason

It would be nice to have an upgrade strategy that can scale in a fully decentralized infrastructure. This strategy should bring:

- minimum human interaction: owner of the 0-OS node should not have to manually update the software running on the node, although the possibility to do so should exist
- Since we can never ensure that all the nodes will be updated and run the same version, we need to have a system that can deal with node using different version of the components
- The publication of a new version should trigger the upgrade all all the nodes automatically, with minimum downtime
- Even though backward compatibility should be the first concern. It will happen that we change an interface or a data format. The automatic upgrade should be able to deal with any migration procedure that could be needed

**Comment by muhamadazmy** [comment]
This sounds awesome, and I think it should be very good if it get to work as suggested. The problem with the "requirements" is that it's too complex to get it to work in such a large scale decentralised setup.

For example, backward compatibility in case of data change. This will make it difficult for example to jump from version 1. to version 3 without going over version 2. Otherwise version 3 should take care of updating data of both version 1 and 2. With time we will keep dragging a lot of code that will be un-maintainable in a very short time. A simple fix is that robot update has to go step by step to the recent release without jumping over versions. In this case each version should grantee backward compatibility only with the previous version. 

May be the robot can detect a new version by checking the hub and update to the next version of his current own version. (DDoS?)

Another issue for example is  with flist <-> template dependency. I don't see a clean way to avoid breakage because the robot updated to the latest templates that is not compatible with the version of jumpscale running other than locking the version of the robot against the version of the templates somehow. This will mean that u can't update the templates without updating (and restarting) the robot.

It will be very tricky if templates started defining the minimum version of jumpscale they need to work. The robot will find hard time finding the right version that satisfies all the templates.

Another simpler fix, is that the robot/templates are all packaged in a single flist and runs as is, no update on the fly. this should go fast since most of the flist has already been downloaded, the only problem is the down time.

I am just writing down my first ideas on the kind of issues that we need to work around to get it to work.

**Comment by rkhamis** [comment]
I think that the way to go here is to give templates a version with indeed, as @muhamadazmy mentioned, upgrade/migration procedure from the previous version and only from the previous version. On starting, the 0-template will check if its services have the same version as its own (in this case, each service must always have the latest version it has run with). If the versions of the template and the service are not the same, the template will run all upgrades from the service's version incrementally until the service is up to date with the template.

I also believe that we should use **tags** on the repo as our version number, not version in the file. Thus, each tightly relevant templates will live in the same repo, and will always have the same version number since their managing robot will probably always be the same. The node robot would then periodically check the repo for new tags and as soon as it finds one, restart the container with the new flists (thus upgrading it)

templates should also have minimum requirements of which versions of templates they're compatible with, and if the minimum requirement is NOT met, then it simply won't communicate with it until its upgrade is done. In case we're always automatically upgrading, this means the robots will be back on track in no time.

**Comment by zaibon** [comment]
> This will make it difficult for example to jump from version 1. to version 3 without going over version 2.

That is very true and like @rkhamis says, this should not be the case, all the upgrade should be incremental and templates should jump from version to version without trying to omit one.

> Another issue for example is with flist <-> template dependency.

This is indeed very tricky since all the services actions are run in the same process as the robot itself, the robot version should always be compatible with all the version required by the templates... This really looks like circular dependencies.

The first idea to distribute template was to use flist, but since 0-os cannot deal with mounting/change flist of a container at runtime, we can't really use flist for this at the moment. 

> templates should also have minimum requirements of which versions of templates they're compatible with, and if the minimum requirement is NOT met, then it simply won't communicate with it until its upgrade is done.

This could be a solution, but then we need to a proper way to define the dependencies between template so the author of the template don't have to deal with this manually in their code. This feature need to be provided by the robot iself in its API

**Comment by rkhamis** [comment]
> This could be a solution, but then we need to a proper way to define the dependencies between template so the author of the template don't have to deal with this manually in their code. This feature need to be provided by the robot itself in its API

I think this would be a little tricky that it's automatically calculated by the robot which versions are compatible. What the robot API can handle is that if the minimum requirement isn't met, it would simply wait until it's compatible. But the compatibility itself should be part of the author's work, because only they would be aware of the changes and the impact of those changes

**Comment by zaibon** [comment]
Let me expose how the robot deals with version currently:
So a template UID is compose of 5 parts, repo host, repo account, repo name, template name and version. Example: `github.com/zero-os/0-templates/node/0.0.1`

to create a new service on a robot you need to specify or full template uid or just his name. 
If we specify just the name, the robot will check if it can identify a template uniquely with only its name. So if there are 2 templates loaded that have the name node it will raise an error.
example: 
the robot have both these template loaded:
`github.com/zero-os/0-templates/vm/0.0.1`
`github.com/openvcloud/0-templates/vm/0.0.1`
trying to create a VM service but just specifying VM for the template won't work.

Also the robot currently doesn't support to have 2 version of the same templates loaded.
Also, when a robot starts, it tried to download all the repos that are needed to load the service installed on it. So if we have a service created from  `github.com/zero-os/0-templates/vm/0.0.1` and the robot is started without the flag `--template-repo githtub.com/zero-os/0-templates`, the robot will clone this repository automatically so it can load the services. In this case, if the version of the templates in the repo is greater that the version of the service, the service gets automatically upgraded by beeing loaded with the new template version. Logic of this can be seen at : https://github.com/zero-os/0-robot/blob/326e28d53c67dd9692efd1e13ff8ac363f297dd1/zerorobot/robot/loader.py#L14-L57

This brings a couple of problem:
- this flow doesn't take in account migration of service between versions.
- there is no way to ask to create a service on a robot by specifying a range of supported version, something like 
- `github.com/zero-os/0-templates/vm/==0.0.1` need to be exactly 0.0.1
- `github.com/zero-os/0-templates/vm/>=0.0.1` need to be 0.0.1 or higher
- `github.com/zero-os/0-templates/vm/>=0.0.1=<0.1.0` need to be between 0.0.1 and 0.1.0

**Comment by zaibon** [comment]
Regarding the auto upgrade of the container running the node robot. I see two approaches:
- 0-OS does the job of monitoring if a new flist is published on the hub. and is responsible to restart the container.This is nice cause this feature could be use for other use case. But this make it hard for the process running in the container to be stopped gracefully before an upgrade of the container
- The node template monitor itself if a new flist is published and is responsible to restart the container. Here is combination with the protected container/process, we could have something that works pretty good. But it feels wrong to do this in this layer. The process would kill itself and expect to be restarted only because the container was started in protected mode.
